### ISSUE TITLE
unable to align markdown tables that has `\|` in its content

### ISSUE THREAD

**Issue by allenfrostline** [kg8m/vim-simple-align#7]
For example, in order to align the following table

```
|A|B|C|
|:-:|:-:|:-:|
|some|random|stu\|ff|
|that|ne\|ed|alignment|
```

using `SimpleAlign` I'm passing command

```
:1,4SimpleAlign \\\@<!|
```

```
| A    | B      | C         |
| :-:  | :-:    | :-:       |
| some | random | stu\|ff   |
| that | ne\|ed | alignment |
```

but truth was nothing happened. Meanwhile, searching using `/\\\@<!|` verifies that the regex should be correct in vim syntax - all delimiter pipes are highlighted and escaped ones are omitted.

Curious where I did wrong or if it's a bug.

**Comment by kg8m** [comment]
@allenfrostline 
Hello, and thanks for your report!

Could you try the following? It performs correctly in my configuration of Vim.

```vim
:1,4SimpleAlign \\\\\\@<!|
```

`SimpleAlign` is a command, so when a pattern including backslashes passed to it, they need to be doubled. This is not a bug but by design. The backslash is a special character, used for example to escape spaces.

**Comment by allenfrostline** [comment]
@kg8m You're 100% correct. Thanks for the help! Closing the issue now.
